FROM debian:latest AS mamba-setup
ARG MAMBA_DIR='/mamba'
ARG MAMBA_INSTALL=mamba-install.sh
SHELL ["/bin/bash", "-c"]
RUN apt-get update && apt-get upgrade -y && apt-get install -y \
        wget
RUN mkdir /download 
RUN wget -O /download/${MAMBA_INSTALL} https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-Linux-x86_64.sh
RUN chmod +x /download/${MAMBA_INSTALL}
RUN /download/${MAMBA_INSTALL} -b -p ${MAMBA_DIR}
# RUN source ${MAMBA_DIR}/etc/profile.d/conda.sh
RUN source ${MAMBA_DIR}/etc/profile.d/mamba.sh
ENV PATH ${MAMBA_DIR}/bin:$PATH
RUN mamba init bash

FROM mamba-setup AS env-setup
ARG ENV_FILE='environment.yml'
COPY ./${ENV_FILE} /app/${ENV_FILE}
RUN mamba env update -n root -f /app/${ENV_FILE}
WORKDIR /app
CMD ["python3"]
