version: "3.9"
services:
  jupyter-lab:
    container_name: 'jupyter-lab'
    platform: "linux/amd64"
    build: 
      dockerfile: ./Dockerfile-mamba
      context: ./
    command: >
      jupyter lab 
      er 
        --port=8889 
        --ip=0.0.0.0 
        --no-browser 
        --IdentityProvider.token=''
        --ServerApp.password=''
        --browser=False
        --ServerApp.disable_check_xsrf=True
    networks:
      - cs6140-network
    ports:
      - '8889:8889'
    volumes:
      - type: bind
        source: .
        target: /app

  flights-db:
    container_name: 'flights-db'
    platform: "linux/amd64"
    build:
      dockerfile: ./Dockerfile-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=flights
    networks:
      - cs6140-network
    ports:
      - '5432:5432'
    volumes:
      - flights-db-volume:/var/lib/postgresql/data

volumes:
  flights-db-volume:

networks:
  cs6140-network:
