version: "3.9"
services:
  jupyter-lab:
    container_name: 'jupyter-lab'
    platform: "linux/amd64"
    build: 
      dockerfile: ./Dockerfile-mamba
      context: ./
    command: >
      jupyter lab 
        --allow-root
        --ServerApp.allow_origin='*'
        --port=8889 
        --ip=0.0.0.0 
        --no-browser 
        --IdentityProvider.token=''
        --ServerApp.password=''
        --browser=False
        --ServerApp.disable_check_xsrf=True
    deploy:
      resources:
        limits:
          memory: 32GB
    networks:
      - cs6140-network
    ports:
      - '8889:8889'
    volumes:
      - type: bind
        source: .
        target: /app

  flights-db:
    container_name: 'flights-db'
    platform: "linux/amd64"
    build:
      dockerfile: ./Dockerfile-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - cs6140-network
    ports:
      - '5432:5432'
    volumes:
      - flights-db-volume:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    platform: "linux/amd64"
    container_name: 'pgadmin'
    restart: always
    networks:
      - cs6140-network
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL : test@test.com
      PGADMIN_DEFAULT_PASSWORD : test
    volumes:
      - pgadmin-volume:/var/lib/pgadmin


volumes:
  flights-db-volume:
  pgadmin-volume:

networks:
  cs6140-network:
