DROP TABLE IF EXISTS flights;
CREATE TABLE flights (
    id      SERIAL      PRIMARY KEY
    Year                                               BIGINT              ,
    Quarter                                            BIGINT              ,
    Month                                              BIGINT              ,
    DayofMonth                                         BIGINT              ,
    DayOfWeek                                          BIGINT              ,
    FlightDate                                         VARCHAR             ,
    Marketing_Airline_Network                          VARCHAR             ,
    Operated_or_Branded_Code_Share_Partners            VARCHAR             ,
    DOT_ID_Marketing_Airline                           BIGINT              ,
    IATA_Code_Marketing_Airline                        VARCHAR             ,
    Flight_Number_Marketing_Airline                    BIGINT              ,
    Originally_Scheduled_Code_Share_Airline            __FILL ME__         ,
    DOT_ID_Originally_Scheduled_Code_Share_Airline     __FILL ME__         ,
    IATA_Code_Originally_Scheduled_Code_Share_Airline  __FILL ME__         ,
    Flight_Num_Originally_Scheduled_Code_Share_Airline __FILL ME__         ,
    Operating_Airline                                  VARCHAR             ,
    DOT_ID_Operating_Airline                           BIGINT              ,
    IATA_Code_Operating_Airline                        VARCHAR             ,
    Tail_Number                                        VARCHAR             ,
    Flight_Number_Operating_Airline                    BIGINT              ,
    OriginAirportID                                    BIGINT              ,
    OriginAirportSeqID                                 BIGINT              ,
    OriginCityMarketID                                 BIGINT              ,
    Origin                                             VARCHAR             ,
    OriginCityName                                     VARCHAR             ,
    OriginState                                        VARCHAR             ,
    OriginStateFips                                    VARCHAR             ,
    OriginStateName                                    BIGINT              ,
    OriginWac                                          VARCHAR             ,
    DestAirportID                                      BIGINT              ,
    DestAirportSeqID                                   BIGINT              ,
    DestCityMarketID                                   BIGINT              ,
    Dest                                               BIGINT              ,
    DestCityName                                       VARCHAR             ,
    DestState                                          VARCHAR             ,
    DestStateFips                                      VARCHAR             ,
    DestStateName                                      VARCHAR             ,
    DestWac                                            BIGINT              ,
    CRSDepTime                                         VARCHAR             ,
    DepTime                                            BIGINT              ,
    DepDelay                                           BIGINT              ,
    DepDelayMinutes                                    DOUBLE PRECISION    ,
    DepDel15                                           DOUBLE PRECISION    ,
    DepartureDelayGroups                               DOUBLE PRECISION    ,
    DepTimeBlk                                         DOUBLE PRECISION    ,
    TaxiOut                                            DOUBLE PRECISION    ,
    WheelsOff                                          VARCHAR             ,
    WheelsOn                                           DOUBLE PRECISION    ,
    TaxiIn                                             DOUBLE PRECISION    ,
    CRSArrTime                                         DOUBLE PRECISION    ,
    ArrTime                                            DOUBLE PRECISION    ,
    ArrDelay                                           BIGINT              ,
    ArrDelayMinutes                                    DOUBLE PRECISION    ,
    ArrDel15                                           DOUBLE PRECISION    ,
    ArrivalDelayGroups                                 DOUBLE PRECISION    ,
    ArrTimeBlk                                         DOUBLE PRECISION    ,
    Cancelled                                          DOUBLE PRECISION    ,
    CancellationCode                                   VARCHAR             ,
    Diverted                                           DOUBLE PRECISION    ,
    CRSElapsedTime                                     __FILL ME__         ,
    ActualElapsedTime                                  DOUBLE PRECISION    ,
    AirTime                                            DOUBLE PRECISION    ,
    Flights                                            DOUBLE PRECISION    ,
    Distance                                           DOUBLE PRECISION    ,
    DistanceGroup                                      DOUBLE PRECISION    ,
    CarrierDelay                                       DOUBLE PRECISION    ,
    WeatherDelay                                       BIGINT              ,
    NASDelay                                           __FILL ME__         ,
    SecurityDelay                                      __FILL ME__         ,
    LateAircraftDelay                                  __FILL ME__         ,
    FirstDepTime                                       __FILL ME__         ,
    TotalAddGTime                                      __FILL ME__         ,
    LongestAddGTime                                    __FILL ME__         ,
    DivAirportLandings                                 __FILL ME__         ,
    DivReachedDest                                     __FILL ME__         ,
    DivActualElapsedTime                               BIGINT              ,
    DivArrDelay                                        __FILL ME__         ,
    DivDistance                                        __FILL ME__         ,
    Div1Airport                                        __FILL ME__         ,
    Div1AirportID                                      __FILL ME__         ,
    Div1AirportSeqID                                   __FILL ME__         ,
    Div1WheelsOn                                       __FILL ME__         ,
    Div1TotalGTime                                     __FILL ME__         ,
    Div1LongestGTime                                   __FILL ME__         ,
    Div1WheelsOff                                      __FILL ME__         ,
    Div1TailNum                                        __FILL ME__         ,
    Div2Airport                                        __FILL ME__         ,
    Div2AirportID                                      __FILL ME__         ,
    Div2AirportSeqID                                   __FILL ME__         ,
    Div2WheelsOn                                       __FILL ME__         ,
    Div2TotalGTime                                     __FILL ME__         ,
    Div2LongestGTime                                   __FILL ME__         ,
    Div2WheelsOff                                      __FILL ME__         ,
    Div2TailNum                                        __FILL ME__         ,
    Div3Airport                                        __FILL ME__         ,
    Div3AirportID                                      __FILL ME__         ,
    Div3AirportSeqID                                   __FILL ME__         ,
    Div3WheelsOn                                       __FILL ME__         ,
    Div3TotalGTime                                     __FILL ME__         ,
    Div3LongestGTime                                   __FILL ME__         ,
    Div3WheelsOff                                      __FILL ME__         ,
    Div3TailNum                                        __FILL ME__         ,
    Div4Airport                                        __FILL ME__         ,
    Div4AirportID                                      __FILL ME__         ,
    Div4AirportSeqID                                   __FILL ME__         ,
    Div4WheelsOn                                       __FILL ME__         ,
    Div4TotalGTime                                     __FILL ME__         ,
    Div4LongestGTime                                   __FILL ME__         ,
    Div4WheelsOff                                      __FILL ME__         ,
    Div4TailNum                                        __FILL ME__         ,
    Div5Airport                                        __FILL ME__         ,
    Div5AirportID                                      __FILL ME__         ,
    Div5AirportSeqID                                   __FILL ME__         ,
    Div5WheelsOn                                       __FILL ME__         ,
    Div5TotalGTime                                     __FILL ME__         ,
    Div5LongestGTime                                   __FILL ME__         ,
    Div5WheelsOff                                      __FILL ME__         ,
    Div5TailNum                                        __FILL ME__         ,
    Duplicate                                          __FILL ME__         ,
);