FROM debian:latest AS mamba-setup
ARG MAMBA_DIR='/mamba'
ARG MAMBA_INSTALL=mamba-install.sh
SHELL ["/bin/bash", "-c"]
RUN apt-get update && apt-get upgrade && apt-get install -y \
    wget
RUN mkdir /download 
RUN wget -O /download/${MAMBA_INSTALL} https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-Linux-x86_64.sh
RUN chmod +x /download/${MAMBA_INSTALL}
RUN /download/${MAMBA_INSTALL} -b -p ${MAMBA_DIR}
# RUN source ${MAMBA_DIR}/etc/profile.d/conda.sh
RUN source ${MAMBA_DIR}/etc/profile.d/mamba.sh
ENV PATH ${MAMBA_DIR}/bin:$PATH
RUN mamba init bash

FROM mamba-setup AS env-setup
ARG ENV_FILE='environment.yml'
COPY ./${ENV_FILE} /app/${ENV_FILE}
# ENV PROJ_ENV=$(cat ${ENV_FILE} | awk 'NR==1{print $2}')
RUN mamba env update -n root -f /app/${ENV_FILE}
# RUN conda env create ${PROJ_ENV}
# RUN mamba env create -f ./${ENV_FILE}
# RUN mamba env create -f ./${ENV_FILE}
# SHELL ["mamba", "run", "-n", "${PROJ_ENV}", "/bin/bash", "-l", "-c"]
# SHELL ["mamba", "run", "-n", "cs6140", "/bin/bash", "-l", "-c"]
# SHELL ["bash", "-l", "-c"
# CMD ["mamba", "run", "-n", "cs6140", "jupyter", "lab", "--allow-root", '--port=8888', '--ip=0.0.0.0']
# CMD ["mamba", "run", "jupyter", "lab", "--allow-root", '--port=8888', '--ip=0.0.0.0']
# CMD mamba run -n cs6140 jupyter lab --allow-root --port=8888 --no-browser --ip=0.0.0.0
# RUN chmod +x /usr/bin/tini
# ENTRYPOINT ["/usr/bin/tini", "--"]
# CMD ["mamba", "run", "jupyter", "lab", "--allow-root", '--port=8888', '--ip=0.0.0.0']
WORKDIR /app
CMD ["python3"]
